CREATE TABLE gboard (
gNo		NUMBER(10)	PRIMARY KEY,
gName     VARCHAR2(20) NOT NULL,
gRegdate   DATE    DEFAULT SYSDATE,
gPw     VARCHAR2(10) NOT NULL
);

CREATE SEQUENCE seq_gboard_pk
START WITH 1
INCREMENT BY 1;